---
version: "3.9"
services:
  identidock:
    build: .
    ports:
      - "5441:5441"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster
  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "5443:8080"
  redis:
    image: redis:latest

